### ISSUE TITLE
Configure lacks an option to disable pyqt5, and build now tries to force it: `ModuleNotFoundError: No module named 'PyQt5'`

### ISSUE THREAD

**Issue by barracuda156** [vectorgraphics/asymptote#494]
```
cd GUI && /opt/local/bin/python3.11 buildtool.py buildui
cd GUI && /opt/local/bin/python3.11 buildtool.py buildicons
Traceback (most recent call last):
  File "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_asymptote/asymptote/work/asymptote-2.94/GUI/buildtool.py", line 9, in <module>
    from PyQt5.uic import compileUiDir
ModuleNotFoundError: No module named 'PyQt5'
make: *** [GUI/xasyqtui] Error 1
make: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_graphics_asymptote/asymptote/work/asymptote-2.94/GUI/buildtool.py", line 9, in <module>
    from PyQt5.uic import compileUiDir
ModuleNotFoundError: No module named 'PyQt5'
make: [GUI/xasyicons] Error 1 (ignored)
make: *** [glrender.o] Error 1
```

Earlier with 2.92 everything was working correctly, pyqt5 was not forced upon, if not detected. Now I do not even see an option in configure to disable it.

**Comment by barracuda156** [comment]
@johncbowman Thank you!
