### ISSUE TITLE
xasy start problem

### ISSUE THREAD

**Issue by norbusan** [vectorgraphics/asymptote#74]
Hi

I am trying to package the latest release of asymptote for Debian (update from 2.44 to 2.47), but xasy has changed considerably, and doesn't start here with the following error:
```
Traceback (most recent call last):
  File "/usr/bin/xasy", line 5, in <module>
    from Window1 import MainWindow1
  File "/usr/share/asymptote/GUI/Window1.py", line 23, in <module>
    import xasy2asy as x2a
  File "/usr/share/asymptote/GUI/xasy2asy.py", line 36, in <module>
    import xasyOptions as xo
  File "/usr/share/asymptote/GUI/xasyOptions.py", line 153, in <module>
    class BasicConfigs:
  File "/usr/share/asymptote/GUI/xasyOptions.py", line 156, in BasicConfigs
    'xasyconfig', os.path.join(_configPath, 'xasyconfig.cson'))
  File "/usr/share/asymptote/GUI/xasyOptions.py", line 80, in __init__
    self.options = self.defaultOptions()
  File "/usr/share/asymptote/GUI/xasyOptions.py", line 38, in defaultOptions
    opt = cson.loads(f.read())
AttributeError: 'NoneType' object has no attribute 'loads'
```
Does the GUI now need additional modules (cson?) that are not imported?

Thanks

**Comment by norbusan** [comment]
cson module is missing on my side, sorry for the noise.
